import Link from "next/link";
import { notFound } from "next/navigation";
import { FileText, Headphones, RotateCcw, Truck } from "lucide-react";
import { prisma } from "@/server/db";
import { requireUser } from "@/server/security";
import { dhakaDate, money } from "@/lib/utils";
import { StatusBadge } from "@/components/status-badge";

export const dynamic = "force-dynamic";

export default async function OrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireUser();
  const { id } = await params;
  const order = await prisma.order.findFirst({ where: { id, userId: user.id }, include: { address: true, items: true, payments: { orderBy: { createdAt: "desc" } }, statusHistory: { orderBy: { createdAt: "asc" } }, shipments: { orderBy: { createdAt: "desc" } }, returns: { select: { id: true, status: true } } } });
  if (!order) notFound();
  const canRequestReturn = order.status === "DELIVERED";
  return <section className="space-y-5 pb-10">
    <header className="kg-card p-5 sm:p-7"><Link href="/account/orders" className="text-sm font-black text-coral">← All orders</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wide text-slate-500">Order</p><h1 className="mt-1 text-3xl font-black text-navy">{order.number}</h1><p className="mt-2 text-sm text-slate-600">Placed {dhakaDate(order.createdAt)}</p></div><div className="flex flex-wrap gap-2"><StatusBadge>{order.status}</StatusBadge><StatusBadge>{order.paymentStatus}</StatusBadge></div></div></header>
    <section className="kg-card p-5 sm:p-7"><h2 className="text-xl font-black text-navy">Order progress</h2><ol className="mt-5 space-y-0">{order.statusHistory.map((row, index) => <li key={row.id} className="grid grid-cols-[24px_1fr] gap-3"><div className="flex flex-col items-center"><span className="mt-1 h-3 w-3 rounded-full bg-teal ring-4 ring-teal/10" />{index < order.statusHistory.length - 1 ? <span className="min-h-12 w-px flex-1 bg-teal/25" /> : null}</div><div className="pb-5"><div className="flex flex-wrap items-center gap-2"><strong className="text-navy">{row.toStatus}</strong><span className="text-xs text-slate-500">{dhakaDate(row.createdAt)}</span></div>{row.note ? <p className="mt-1 text-sm text-slate-600">{row.note}</p> : null}</div></li>)}</ol></section>
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section className="kg-card p-5 sm:p-7"><h2 className="text-xl font-black text-navy">Products</h2><div className="mt-4 divide-y divide-[var(--border)]">{order.items.map(item => <div key={item.id} className="grid grid-cols-[1fr_auto] gap-4 py-4 first:pt-0 last:pb-0"><div><strong className="text-navy">{item.name}</strong><p className="mt-1 text-sm text-slate-500">SKU {item.sku} · Quantity {item.quantity}</p></div><strong className="text-navy">{money(Number(item.unitPrice) * item.quantity - Number(item.discount))}</strong></div>)}</div></section><section className="kg-card p-5 sm:p-7"><h2 className="text-xl font-black text-navy">Payment summary</h2><dl className="mt-4 space-y-3 text-sm"><Row label="Subtotal" value={money(Number(order.subtotal))} /><Row label="Discount" value={`−${money(Number(order.discount))}`} /><Row label="Delivery" value={money(Number(order.deliveryFee))} /><div className="border-t border-[var(--border)] pt-3"><Row label="Total" value={money(Number(order.total))} strong /></div></dl><p className="mt-4 text-sm text-slate-600">{order.paymentMethod} · {order.paymentStatus}</p>{order.payments[0]?.reference ? <p className="mt-1 break-all text-xs text-slate-500">Reference {order.payments[0].reference}</p> : null}</section></div>
    <div className="grid gap-5 md:grid-cols-2"><section className="kg-card p-5 sm:p-7"><h2 className="text-xl font-black text-navy">Shipping address</h2><div className="mt-3 text-sm leading-6 text-slate-600">{order.address ? <><strong className="block text-navy">{order.address.name} · {order.address.label}</strong><p>{order.address.line1}{order.address.landmark ? `, ${order.address.landmark}` : ""}</p><p>{[order.address.area, order.address.district, order.address.division].filter(Boolean).join(", ")}</p><p>{order.address.phone}</p></> : <p>Shipping details are recorded on this order.</p>}</div></section><section className="kg-card p-5 sm:p-7"><h2 className="flex items-center gap-2 text-xl font-black text-navy"><Truck className="h-5 w-5 text-teal" /> Delivery</h2><dl className="mt-3 space-y-2 text-sm text-slate-600"><Row label="Method" value={order.deliveryMethod} /><Row label="Zone" value={order.deliveryZoneName ?? "—"} /><Row label="Courier" value={order.courierProvider ?? "Not assigned"} /><Row label="Tracking" value={order.trackingId ?? "Not available yet"} /></dl></section></div>
    <section className="kg-card flex flex-wrap gap-2 p-5"><Link href={`/account/orders/${order.id}/invoice`} className="kg-button kg-button-secondary"><FileText className="h-4 w-4" /> Invoice</Link><Link href={`/account/support?order=${order.id}`} className="kg-button kg-button-secondary"><Headphones className="h-4 w-4" /> Get support</Link>{canRequestReturn ? <Link href="/account/returns" className="kg-button kg-button-primary"><RotateCcw className="h-4 w-4" /> Request return</Link> : null}</section>
  </section>;
}

function Row({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <div className={`flex justify-between gap-4 ${strong ? "text-base font-black text-navy" : ""}`}><dt>{label}</dt><dd className="text-right font-bold">{value}</dd></div>; }
